<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

genesis_structural_wrap( 'site-inner', 'close' );
echo '</div>'; //* end .site-inner or #inner

do_action( 'genesis_before_footer' );
do_action( 'genesis_footer' );
do_action( 'genesis_after_footer' );

echo '</div>'; //* end .site-container or #wrap

do_action( 'genesis_after' );
wp_footer(); //* we need this for plugins
?>

  <!-- Custom AirPair Analytics -->
  <script type="text/javascript">

    function initPage()
    {
      window.useOlark = true;
      require('scripts/providers/all');
      categories = '';
      jQuery(".entry-categories a").each(function(a){
        categories+=jQuery(a).text()+",";
      });
      addjs.trackEvent('page','view', window.location.pathname, {categories:categories});
    }

  </script>
  <script src="//airpair.com/javascripts/providers.js" defer onload="initPage()"></script>
</body>
</html>
